[package]
name = "min-chat"
version = "0.1.0"
authors = ["eignnx <eignnx@gmail.com>"]

[[bin]]
name = "server"
path = "src/server/main.rs"

[dependencies]
dotenv = "0.11.0"
dotenv_codegen = "0.11.0"

serde = "1.0.44"
serde_derive = "1.0.44"
serde_json = "^1.0"

websocket = "0.20.2"